INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21'); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21'); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21'); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21'); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21'); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21'); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21'); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21'); 
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flurb", "Toy", 10, '12/15/20', '1/15/21');


INSERT INTO users (name, age) VALUES ("Krae", 25);
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25);
INSERT INTO users (name, age) VALUES ("Krae", 25);
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25); 
INSERT INTO users (name, age) VALUES ("Krae", 25);


INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2); 
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);